In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data.head()

Group_1  Group_2  Group_3  Group_4  Month  Week_day  \
0        0        0        0        1      7         1   
1        0        0        0        0      7         1   
2        0        0        0        1      7         2   
3        1        0        0        0      7         3   
4        0        0        0        1      7         3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [4]:
data.describe()

Group_1     Group_2     Group_3     Group_4      Month    Week_day  \
count  700.000000  700.000000  700.000000  700.000000  700.00000  700.000000   
mean     0.250000    0.008571    0.090000    0.597143    6.36000    2.011429   
std      0.433322    0.092250    0.286386    0.490823    3.50501    1.480396   
min      0.000000    0.000000    0.000000    0.000000    1.00000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    3.00000    1.000000   
50%      0.000000    0.000000    0.000000    1.000000    6.00000    2.000000   
75%      0.250000    0.000000    0.000000    1.000000   10.00000    3.000000   
max      1.000000    1.000000    1.000000    1.000000   12.00000    6.000000   

       Transportation Expense  Distance to Work         Age  \
count              700.000000        700.000000  700.000000   
mean               222.347143         29.892857   36.417143   
std                 66.312960         14.804446    6.379083   
min                118.000000          5.000000   27.000000   
25%                179.000000         16.000000   31.000000   
50%                225.000000         26.000000   37.000000   
75%                260.000000         50.000000   40.000000   
max                388.000000         52.000000   58.000000   

       Daily Work Load Average  Body Mass Index   Education    Children  \
count               700.000000       700.000000  700.000000  700.000000   
mean                271.801774        26.737143    0.167143    1.021429   
std                  40.021804         4.254701    0.373370    1.112215   
min                 205.917000        19.000000    0.000000    0.000000   
25%                 241.476000        24.000000    0.000000    0.000000   
50%                 264.249000        25.000000    0.000000    1.000000   
75%                 294.217000        31.000000    0.000000    2.000000   
max                 378.884000        38.000000    1.000000    4.000000   

             Pets  Absenteeism Time in Hours  
count  700.000000                 700.000000  
mean     0.687143                   6.761429  
std      1.166095                  12.670082  
min      0.000000                   0.000000  
25%      0.000000                   2.000000  
50%      0.000000                   3.000000  
75%      1.000000                   8.000000  
max      8.000000                 120.000000

In [5]:
targets=np.where(data['Absenteeism Time in Hours']<=data['Absenteeism Time in Hours'].median(),0,1)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data['Excessive Absenteeism']=targets

In [7]:
data=data.drop('Absenteeism Time in Hours',axis=1)

In [8]:
data

Group_1  Group_2  Group_3  Group_4  Month  Week_day  \
0          0        0        0        1      7         1   
1          0        0        0        0      7         1   
2          0        0        0        1      7         2   
3          1        0        0        0      7         3   
4          0        0        0        1      7         3   
..       ...      ...      ...      ...    ...       ...   
695        1        0        0        0      5         2   
696        1        0        0        0      5         2   
697        1        0        0        0      5         3   
698        0        0        0        1      5         3   
699        0        0        0        1      5         3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0                 30          0         2     1                      1  
1                 31          0         1     0                      0  
2                 31          0         0     0                      0  
3                 24          0         2     0                      1  
4                 30          0         2     1                      0  
..               ...        ...       ...   ...                    ...  
695               22          1         2     0                      1  
696               24          0         1     2                      0  
697               25          1         0     0                      1  
698               25          1         0     0                      0  
699               25          0         1     1                      0  

[700 rows x 15 columns]

In [9]:
inputs=data.iloc[:,:-1]
inputs

Group_1  Group_2  Group_3  Group_4  Month  Week_day  \
0          0        0        0        1      7         1   
1          0        0        0        0      7         1   
2          0        0        0        1      7         2   
3          1        0        0        0      7         3   
4          0        0        0        1      7         3   
..       ...      ...      ...      ...    ...       ...   
695        1        0        0        0      5         2   
696        1        0        0        0      5         2   
697        1        0        0        0      5         3   
698        0        0        0        1      5         3   
699        0        0        0        1      5         3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [10]:
targets=data.iloc[:,-1]
targets

0      1
1      0
2      0
3      1
4      0
      ..
695    1
696    0
697    1
698    0
699    0
Name: Excessive Absenteeism, Length: 700, dtype: int64

In [11]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [12]:
inputs=preprocessing.scale(inputs)

In [13]:
inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [14]:
inputs.shape

(700, 14)

# Splitting the data

In [15]:
x_train,x_test,y_train,y_test=train_test_split(inputs,targets,test_size=0.2,random_state=69)

In [16]:
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score

In [17]:
reg=LogisticRegression()

In [18]:
reg.fit(x_train,y_train)

LogisticRegression()

In [19]:
reg.score(x_train,y_train)

0.7714285714285715

In [20]:
prediction=reg.predict(x_train)

In [21]:
x_train is prediction

False

In [23]:
accuracy_score(prediction,y_train)

0.7714285714285715

In [24]:
features=data.iloc[:,:-1].columns.values
features

array(['Group_1', 'Group_2', 'Group_3', 'Group_4', 'Month', 'Week_day',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [25]:
summary=pd.DataFrame(columns=['Feature Name'],data=features)

In [26]:
coef=reg.coef_

In [27]:
reg.intercept_

array([-0.25458624])

In [28]:
summary['Weights']=np.transpose(coef)

In [29]:
summary

Feature Name   Weights
0                   Group_1  2.042657
1                   Group_2  0.343858
2                   Group_3  1.407910
3                   Group_4  1.254124
4                     Month  0.053998
5                  Week_day -0.203772
6    Transportation Expense  0.717107
7          Distance to Work -0.108999
8                       Age -0.277187
9   Daily Work Load Average -0.073659
10          Body Mass Index  0.353233
11                Education -0.036039
12                 Children  0.448266
13                     Pets -0.332646

In [30]:
reg.score(x_test,y_test)

0.75

# Savig the model

In [31]:
import pickle

In [32]:
with open('model','wb') as file:
    pickle.dump(reg,file)

In [34]:
reg.predict_proba(x_train)

array([[0.34787681, 0.65212319],
       [0.57552719, 0.42447281],
       [0.66016472, 0.33983528],
       ...,
       [0.4874264 , 0.5125736 ],
       [0.98737067, 0.01262933],
       [0.85596421, 0.14403579]])